token = "token"
prefix = '!'
driverPath = "chromedriver"
filepath = "/home/victor/instaScraper/media/"
scrollTime = 5
followerXpath = """//*[@id="react-root"]/section/main/div/header/section/ul/li[2]/a/span"""
timeXpath = """//*[@id="react-root"]/section/main/div/div/article/div[3]/div[2]/a/time"""
connentXpath = """//meta[@property="og:type"]"""
likesXpath = """//*[@id="react-root"]/section/main/div/div/article/div[3]/section[2]/div/div/button"""