token = "NzM3MTc3MjYzNjA2NDY0NTEz.Xx5j0w.8dsXyggHXrA7sIR63X8oxTgwKzw"
jsonPath = "/instaScraper/configs.json"
followerXpath = """//*[@id="react-root"]/section/main/div/header/section/ul/li[2]/a/span"""
timeXpath = """//*[@id="react-root"]/section/main/div/div/article/div[3]/div[2]/a/time"""
connentXpath = """//meta[@property="og:type"]"""
likesXpath = """//*[@id="react-root"]/section/main/div/div/article/div[3]/section[2]/div/div/button"""